In [30]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import normalize

In [2]:
df = pd.read_csv('iris.data',header=None)

In [3]:
df.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [4]:
data = df.drop(df.columns[[4]], axis=1)
target = df[4]
data.head()


0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [5]:
# Standardizing the features
data = StandardScaler().fit_transform(data)

In [11]:
pca = PCA(n_components=3)

In [12]:
pca.fit(data) 

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [13]:
print(pca.explained_variance_ )  

[2.93035378 0.92740362 0.14834223]


In [14]:
print(pca.components_)

[[ 0.52237162 -0.26335492  0.58125401  0.56561105]
 [ 0.37231836  0.92555649  0.02109478  0.06541577]
 [-0.72101681  0.24203288  0.14089226  0.6338014 ]]


In [15]:
n_targets = 3
n_features = df.shape[1]-1
n_features

4

In [16]:
def multiplicationByColumn(u, y):
    lista = []
#     print(u.shape[1])
    for i in range(u.shape[1]):
#         print(u[:, i])
#         print('u[:, i] * y: ', np.sum((u[:, i] * y)))
        lista.append(np.sum(u[:, i] * y))
    lista = np.matrix(lista).T
#     print(lista)
    return lista

In [17]:
u = np.array([[2, 2], [3, 0]])
y = np.array([1 ,2])
# print(u.shape)
multiplicationByColumn(u, y)

matrix([[8],
        [2]])

In [18]:
# number_components
# w = np.random.uniform(low = 0, high = 1, size = [number_components, n_features])
# u = np.triu(np.random.uniform(low = 0, high = 1, size = [n_targets, n_targets]), 1)

# print(w.shape)
# print(u.shape)

# idxs = np.arange(len(data))


# np.random.shuffle(idxs)
# # aux = target[idxs[0]]

# if aux == 'Iris-setosa':
#     y = [1, 0, 0]
# elif aux == 'Iris-versicolor':
#     y = [0, 1, 0]
# elif aux == 'Iris-virginica':
#     y = [0, 0, 1]
# y = np.matrix(np.array(y)).T
# # print(y)


# init_learning_rate = 0.4
# init_learning_side = 0.5
# # alpha = 0.5

# n_iterations =150
# # print('-'*50)
# # print(u)
# # print(y)
# # print(u*y)



# print('-'*50)

# for i in range(n_iterations):
#     rnd = np.random.randint(0, 150)
    
#     aux = target[rnd]
#     if aux == 'Iris-setosa':
#         y = [1, 0, 0]
#     elif aux == 'Iris-versicolor':
#         y = [0, 1, 0]
#     elif aux == 'Iris-virginica':
#         y = [0, 0, 1]
#     y = np.matrix(np.array(y)).T


#     item = data[rnd]
#     aux_item = np.matrix(item)
#     termino_1 = ((w * aux_item.T))        
# #     termino_2 = (((u * y)))
#     termino_2 = multiplicationByColumn(u, y)
# #     print(termino_2)

#     y = termino_1 + termino_2    
#     delta_w = init_learning_rate * (y * aux_item)
#     w = w + delta_w

#     scaler = MinMaxScaler()
#     scaler.fit(w)
#     w = scaler.transform(w)
# #     print((y * y.T).shape)
#     delta_u =  -1*(init_learning_side * (y * y.T))

#     u = u + delta_u
#     u = np.triu(u, 1) 
# #     print(u)
        
    
    
# print('w:',w)
# print('u:',u)
    
    

In [289]:
number_components = 3
w = np.random.uniform(low = 0, high = 1, size = [number_components, n_features])
w = normalize(w, norm='l2')
# u = np.tril(np.random.uniform(low = 0, high = 1, size = [number_components, number_components]), -1)
u = np.triu(np.random.uniform(low = 0, high = 1, size = [number_components, number_components]), 1)


print(w.shape)
print(u.shape)
init_learning_rate = 0.01
init_learning_side = 0.01
factor = 0.1
n_iterations =350
# number_components = 4
momentum_w = np.zeros(w.shape)
momentum_u = np.zeros(u.shape)
momentum = 0.65
limiar = 0.9

for i in range(n_iterations):
    rnd = np.random.randint(0, 150)
    item = data[rnd]

    YR = np.zeros(number_components)
    for j in range(number_components):        
        if j == 0:                      
#             y1 = np.sum(w[:,0] * item)
#             delta_w = (init_learning_rate * y1 * item)
#             w[:,0] = w[:,0] + delta_w + (momentum * momentum_w[:,0])
#             momentum_w[:,0] = delta_w                                
#             w1 = w[:,0]
            
            y1 = np.sum(w[0,:] * item)
            delta_w = (init_learning_rate * y1 * item)
            w[0,:] = w[0,:] + delta_w + (momentum * momentum_w[0,:])
            momentum_w[0,:] = delta_w                                
            w1 = w[0,:]
            YR[j] = y1
        else:
#             yj = np.sum(w[:,j] * item) + np.sum(u[:,j] * YR)
# #             w[:,j] = w1 + (init_learning_rate * yj * item)
#             delta_w = (init_learning_rate * yj * item)
#             delta_u = (init_learning_side * yj * YR)
#             w[:,j] = w[:,j] + delta_w + (momentum * momentum_w[:,j])
#             u[:,j] = u[:,j] - delta_u + (momentum * momentum_u[:,j])
            
#             momentum_w[:,j] = delta_w            
#             momentum_u[:,j] = delta_u
#             print('u[:,j]: ', (u[:,j]).shape)
#             print('YR: ', YR.shape)
            yj = np.sum(w[j,:] * item) + np.sum(u[:,j]  * YR)
#             w[:,j] = w1 + (init_learning_rate * yj * item)
            delta_w = (init_learning_rate * yj**2 * item)
            delta_u = (init_learning_side * yj**2 * YR)
            w[j, :] = w[j, :] + delta_w + (momentum * momentum_w[j, :])
            u[j, :] = u[j, :] - delta_u + (momentum * momentum_u[j, :])
            
            momentum_w[j,:] = delta_w
            momentum_u[j,:] = delta_u
                        
#             u = np.tril(u, -1)
            u = np.triu(u, 1)
            YR[j] = yj
#     init_learning_rate = max(0.0001, (factor * init_learning_rate))
#     init_learning_side = max(0.0002, (factor * init_learning_side))
#     momentum = max(0.0001, (factor * momentum))
        
            
#     scaler = MinMaxScaler()
#     scaler.fit(w)
#     w = scaler.transform(w)
    w = normalize(w, norm='l2')
    suma_weights = np.sum(np.amax(np.absolute(u), axis = 0))
#     if suma_weights < limiar:
#         print('limiar')
#         break
print(w)
# print(w.T)
# print(u)
    
    
            
    

(3, 4)
(3, 3)
[[ 0.51667381 -0.3079717   0.56061374  0.56913429]
 [ 0.57612096  0.77442212  0.17471544  0.19449817]
 [-0.39464325  0.58618126 -0.54048476 -0.45664478]]


In [258]:
# [[ 0.52237162 -0.26335492  0.58125401  0.56561105]
#  [ 0.37231836  0.92555649  0.02109478  0.06541577]
#  [-0.72101681  0.24203288  0.14089226  0.6338014 ]]